[template variables]
ATM_PROCX=8
ATM_PROCY=8
BASIS=1978,9,1,0,0,0
CICE_COL=1440
CICE_ROW=1205
CLOCK=0,25,0
COMPUTE_HOST='exab'
!!EXTRACT_HOST='$ROSE_ORIG_HOST'
FCM_VERSION=''
GIT_LOC='git@github.com:'
!!GIT_MIRROR_LOC='localmirrors:'
HOUSEKEEPING=true
IOS_NPROC=0
NEMO_IPROC=15
NEMO_JPROC=17
POSTPROC_HOST='$ROSE_ORIG_HOST'
RCF_PROCX=4
RCF_PROCY=8
REMOTE_PP=false
SPLIT_PP=true
SYSTEM_NAME='meto_azspice'
USE_LINUX_SERVER=true
USE_MIRRORS=false
VERBOSE=true
XIOS_NPROC=6
