meta=../../../rose-meta/archive_and_meaning/pp_build/HEAD

[command]
default=$SOURCE_DIRECTORY/moci/Postprocessing/build/build_pp.sh

[env]
!MOCILIB=true
!MOCILIB_PATH=SOURCE_DIRECTORY/moci/mocilib
NEMO_TOOLS=fcm:nemo.xm/utils/tools_r4.0-HEAD
NEMO_TOOLS_REV=@16016
!PP_COMPONENTS=atmos nemocice unicicles archive_verify
PP_SOURCE_DIR=$SOURCE_DIRECTORY/moci
!PP_TARGET_DIR=$CYLC_WORKFLOW_SHARE_DIR/bin
PP_TESTS=true

# Icebergs not currently used in rose-stem - nemotools not required
[file:$PP_SOURCE_DIR/../nemotools/icb_combrest.py]
source=$NEMO_TOOLS/REBUILD_NEMO/icb_combrest.py$NEMO_TOOLS_REV

[!file:$PP_SOURCE_DIR/../nemotools/icb_pp.py]
source=$NEMO_TOOLS/MISCELLANEOUS/icb_pp.py$NEMO_TOOLS_REV
