[env=MOCILIB]
compulsory=false
description=Include MOCILIB library source
help=Include the MOCILIB library in PostProc app build
    =
    =Default: True
ns=Configuration
sort-key=build3a
trigger=env=MOCILIB_PATH : true
type=boolean

[env=MOCILIB_PATH]
compulsory=false
description=Path to the MOCILIB library source
help=Path to the MOCILIB library source extracted from Git repository or local source
    =
    =Default: $PP_SOURCE_DIR/mocilib
ns=Configuration
sort-key=build3b

[env=PP_COMPONENTS]
compulsory=false
description=Model components
help=List of model components to be included in the PostProc app build
    =
    =Default: atmos nemocice unicicles archive_verify
length=:
ns=Configuration
sort-key=build1

[env=PP_SOURCE_DIR]
compulsory=false
description=Extracted source directory for the MOCI PostProc application
help=Path to the MOCI post-processing app source, extracted from the Git Repository or local source
    =
    =Default: $CYLC_WORKFLOW_SHARE_DIR/source/moci_postproc
ns=Configuration
sort-key=build2a

[env=PP_TARGET_DIR]
compulsory=false
description=Extracted source directory for the MOCI PostProc application
help=Build path for the MOCI post-processing app source
    =
    =Default: $CYLC_WORKFLOW_SHARE_DIR/bin
ns=Configuration
sort-key=build2b

[env=PP_TESTS]
compulsory=false
description=Include PostProc app unittests
help=Include all unit tests in PostProc application build
    =
    =Default: false
ns=Configuration
sort-key=buildtests
type=boolean

[file:$PP_SOURCE_DIR/../nemotools/icb_combrest.py]
compulsory=false
description=Nemo iceberg restart file rebuild script

[file:$PP_SOURCE_DIR/../nemotools/icb_combrest.py=source]
pattern=.*icb_pp\.py.*

[file:$PP_SOURCE_DIR/../nemotools/icb_pp.py]
compulsory=false
description=Nemo iceberg trajectory file rebuild script
