meta=coupled_drivers/plot_loadbalance/drivers_2.0.1

[command]
default=run_python_env.sh $SOURCE_DIRECTORY/moci/Coupled_Drivers/driver_utilities/plot_cpmip_summary/plot_cpmip_summary.py --input-file cpmip.output --filename plot_out.png
