[command]
default=echo "[INFO] Extracting UM and related repositories"

[file:$SOURCE_DIRECTORY/casim]
source=git:${GIT_LOC}MetOffice/casim.git::./::2025.12.1

[file:$SOURCE_DIRECTORY/jules]
source=git:${GIT_LOC}/MetOffice/jules.git::./::2025.12.1

[file:$SOURCE_DIRECTORY/shumlib]
source=git:${GIT_LOC}MetOffice/shumlib.git::./::2025.10.1

[file:$SOURCE_DIRECTORY/socrates]
source=git:${GIT_LOC}MetOffice/socrates.git::./::2025.12.1

[file:$SOURCE_DIRECTORY/ukca]
source=git:${GIT_LOC}MetOffice/ukca.git::./::2025.12.1

[file:$SOURCE_DIRECTORY/um]
# UM repository is private - Use local mirror
source=git:${GIT_LOC}MetOffice/um.git::./::vn14.0
