#!/usr/bin/env bash
#*****************************COPYRIGHT******************************
# (C) Crown copyright 2021-2025 Met Office. All rights reserved.
#
# Use, duplication or disclosure of this code is subject to the restrictions
# as set forth in the licence. If no licence has been raised with this copy
# of the code, the use, duplication or disclosure of it is strictly
# prohibited. Permission to do so must first be obtained in writing from the
# Met Office Information Asset Owner at the following address:
#
# Met Office, FitzRoy Road, Exeter, Devon, EX1 3PB, United Kingdom
#*****************************COPYRIGHT******************************
# NAME
#     run_model
#
# DESCRIPTION
#     Run the drivers (via link_drivers), export the environment variables
#     as required (via driver_envar), run the model (via driver_cmd) and
#     finalize the model using the drivers (via link_drivers --finalize)

# Fail if environment variables are unset, for sanitys sake
set -eu

echo $CYLC_SUITE_RUN_DIR

# Set a default value for the driver extract directory to allow for backward
# compatibility, and future flexibility
DRIVER_EXTRACT_DIR=${DRIVER_EXTRACT_DIR:=$CYLC_SUITE_SHARE_DIR/fcm_make_drivers}

echo "[DRIVER_TEST_SCRIPT] DRIVER_EXTRACT_DIR is $DRIVER_EXTRACT_DIR" 

# This lets us set up a failure mode
export DRIVERS_FINALISED=false

# Are we using the mct_validate utility to check on the coupled model setup
# Must be set to true to run validation
L_MCT_VALIDATE=${L_MCT_VALIDATE:=false}


# Copy scripts to work directory so they can be found. We use the dependency
# checker script so we only copy the files we need.
if [[ $DRIVER_EXTRACT_DIR == *"fcm_make"* ]] ; then
    # fcm_make infrastructure
    extract_path=extract/drivers
else
    extract_path=
fi
FILES_TO_INSTALL=$($DRIVER_EXTRACT_DIR/$extract_path/Coupled_Drivers/driver_dependencies.py --extract-directory $DRIVER_EXTRACT_DIR/$extract_path/Coupled_Drivers)
for file in $FILES_TO_INSTALL; do
    # handle any packages
    package_name=$(dirname "${file}")
    if [[ $package_name != '.' && ! -d $package_name ]]; then
	mkdir $package_name
    fi
    # as package_name will default to . then this will handle all cases
    cp $DRIVER_EXTRACT_DIR/$extract_path/Coupled_Drivers/$file $package_name
done

# If the run uses LFRic, and environment variable NAMCOUPLE_STATIC is .false.
# then we need to use the NGMS_utils libraries. NAMCOUPLE_STATIC is not a
# compulsory environment variable, so we set a default for backward
# compatibility
NAMCOUPLE_STATIC=${NAMCOUPLE_STATIC:=True}
if [[ "$models" == *lfric* && "$NAMCOUPLE_STATIC" == .false. ]]; then
    cp $DRIVER_EXTRACT_DIR/$extract_path/Utilities/NGMS_utils/ngms_namcouple_gen/*py ./
    cp $DRIVER_EXTRACT_DIR/$extract_path/Utilities/NGMS_utils/ngms_suite_lib/*py ./
fi

EXTRA_LINK_DRIVERS_INFO=$( echo ${EXTRA_LINK_DRIVERS_INFO:-} | tr '[:upper:]' '[:lower:]')
if [[ ${EXTRA_LINK_DRIVERS_INFO:-} == "true" ]]; then
    stat ./
    stat ./link_drivers
    lfs getstripe --mdt-index ./link_drivers
    lfs getstripe ./link_drivers
fi

# Run our drivers, this produces two command files
#  driver_envar containing environment variables to be exported
#  driver_cmd containing a command for the system launcher
./link_drivers --run

echo '[DRIVER_TEST_SCRIPT] Drivers successfully linked'

# Validate mct setup if required. This must be done after the link stage to
# ensure that any dynamic namcouple setup, namelist setup, and file moving
# had been completed
if [ "$L_MCT_VALIDATE" = True ]; then
    echo "Running MCT validate"
    cp $DRIVER_EXTRACT_DIR/$extract_path/Coupled_Drivers/driver_utilities/mct_validate/mct_validate.py ./
    ./mct_validate.py
fi

# Process after any failures
SIGNALS='EXIT'
FINALLY() {
    echo "Finally!"
    for S in $SIGNALS; do
        trap '' $S #switch off traps
    done
    if [ "$DRIVERS_FINALISED" = true ]; then
        echo "Completed successfully"
    else
        echo 'Trying to run driver in failure mode'
        ./link_drivers --failure
    fi
}

for S in $SIGNALS; do
    trap 'FINALLY' $S
done

# Export the enviromnent variables from all the drivers
source driver_envar
# Run the MPI launcher command and provide timing information if required
start=$(date +%s)
source driver_cmd
end=$(date +%s)

time_in_launcher=$((end-start))
echo "[DRIVER_TEST_SCRIPT] $time_in_launcher seconds are spent in the"
echo "[DRIVER_TEST_SCRIPT] MPI Launcher"

#export time_in_launcher variable so the cpmip controller can find it 
#if required
export time_in_launcher

# Run the drivers in finalize mode (after completion of the model). This deals
# with model standard out / standard error, and also with any file details
# required prior to the start of the next model cycle (if applicable). If
# the MPI launcher has failed, we run the drivers in a stripped down failure 
# mode
echo '[DRIVER_TEST_SCRIPT] Finalizing drivers'
./link_drivers --finalize;
export DRIVERS_FINALISED=true
