[template variables]
BUILD_MCT=true
BUILD_TEST=true
EXTRACT_OASIS=true
GC_PRG_ENV_NAME='GC5-PrgEnv'
GC_PRG_ENV_VERSION='test_git_20251219'
HPC_HOST='exab'
HPC_HOST_USERNAME='moci'
MODULE_CMD='module load cpe/23.05; module load cray-libsci; module load cray-hdf5-parallel; module load cray-netcdf-hdf5parallel; module swap cce/15.0.0'
OASIS_BRANCH='20b37bfb'
OASIS_BUILD_DIR='crayEX'
OASIS_MOD_NAME='oasis3-mct_4.0'
OASIS_MOD_VERSION='test_git_20251219'
OASIS_REPOSITORY='https://gitlab.com/cerfacs/oasis3-mct.git'
!!OASIS_WC_DIR='/data/users/hshep/oasis_srcs/oasis3-mct'
PLATFORM_CONFIG='make.crayEX'
XIOS_MOD_NAME='XIOS-2.5'
XIOS_MOD_VERSION='test_git_20251219'
XIOS_ONLY=false
!!XIOS_PRG_ENV_NAME='XIOS_2.5-PrgEnv'
!!XIOS_PRG_ENV_VERSION='2023-03-ticket613-cpe22.11'
XIOS_REV=1873
XIOS_URL='fcm:xios.xm'
XIOS_VERSION='branchs/xios-2.5'
